pulse-cloud-dev/pulse-front-v2

- src/shared/components/widgets/checkbox/utils/checkboxManager.ts
>all 체크박스와 하위 항목 체크 박스 상태 연동 처리에 대한 코드 리뷰 요청
> [feat] 체크박스 수정

- src/app/configs/route.config.tsx
- src/app/styles/component/form.css
- src/app/styles/component/page.css
- src/contracts/request/auth/find.request.dto.ts
- src/contracts/request/index.ts
- src/contracts/response/auth/find.response.ts
- src/contracts/response/index.ts
- src/features/auth/finds/find.controller.tsx
- src/features/auth/finds/find.service.ts
- src/features/auth/finds/findPassWord.view.tsx
- src/networks/apis/user.api.ts
- src/networks/client/private.client.ts
- src/networks/client/public.client.ts
- src/shared/components/atoms/typographys/typography.tsx
- src/shared/components/widgets/forms/components/dynamicForm.tsx
- src/shared/constants/const/form.const.ts
> Pulse 226 회원가입 페이지 퍼블리싱 api연동

- src/app/configs/route.config.tsx
- src/features/auth/signIn/signIn.view.tsx
- src/features/auth/signUp/signUp.service.ts
- src/features/auth/signUp/steps/signupformstep.tsx
- src/shared/constants/const/url.const.ts
> chore:경로 수정

- src/features/auth/signUp/steps/signupformstep.tsx
> feat:api 연동 (request user)

- src/networks/client/public.client.ts
> Feat:api경로수정

- src/features/auth/signUp/steps/signupformstep.tsx
> bug:json데이터 입출력값 수정

- src/features/auth/signUp/signUp.view.tsx
- src/features/auth/signUp/steps/signupformstep.tsx
> bug:json데이터 입출력값 수정(phonenumber -제거)

- src/app/styles/common/guide.css
- src/features/auth/signUp/signUp.controller.tsx
- src/features/auth/signUp/signUp.service.ts
- src/features/auth/signUp/steps/signupformstep.tsx
- src/networks/apis/user.api.ts
- src/shared/components/widgets/forms/components/formField.tsx
- src/shared/components/widgets/headers/navigation/mainNavigation.tsx
> Pulse 272 회원가입 api 중복 회원가입 방지 formfield 디자인 수정 password schema수정

- README.md
- package-lock.json
- package.json
- src/app/configs/route.config.tsx
- src/app/styles/component/form.css
- src/features/auth/finds/find.controller.tsx
- src/features/auth/finds/findPassWord.view.tsx
- src/networks/apis/user.api.ts
- src/shared/components/widgets/forms/components/dynamicForm.tsx
- src/shared/components/widgets/rePassword/step/naverLogin.tsx
- src/shared/components/widgets/rePassword/step/rePasswordForm.tsx
- src/shared/components/widgets/rePassword/step/showEmail.tsx
- src/shared/components/widgets/rePassword/type/useRePasswordForm.ts
- src/shared/constants/const/form.const.ts
> Pulse 206 feature login

- src/features/auth/signUp/steps/stepthreeauth.tsx
> hotfix:회원가입 버그 수정

- src/networks/apis/user.api.ts
> hotfix:eamil파라미터 값 수정

- src/app/styles/component/pageNation.css
- src/app/styles/component/popup.css
- src/shared/components/widgets/popups/local/components/localPopupHeader.tsx
> 스타일 수정
- 지역 모달 className
- 모달 검색바 스크롤바 추가
> Pulse 345 followup

- index.html
- src/app/styles/component/alert.css
- src/shared/modules/alerts/alert.tsx
- src/shared/modules/alerts/alertTypes.ts
> Pulse 382 멘토링 상세페이지

- public/icons/chevron_down_bk_16.svg
- src/app/styles/component/form.css
- src/features/auth/signUp/signUp.view.tsx
- src/features/auth/signUp/steps/signupconsentstep.tsx
- src/features/auth/signUp/steps/signupformstep.tsx
- src/features/auth/signUp/steps/stepthreeauth.tsx
- src/features/posts/posts.view.tsx
- src/features/register/formsections/career.tsx
- src/features/register/formsections/certificate.tsx
- src/features/register/formsections/education.tsx
- src/features/register/formsections/job.tsx
- src/features/register/formsections/stack.ts
- src/features/register/register.controller.tsx
- src/networks/apis/register.api.ts
- src/shared/components/blocks/datepicker/DatePickerField.tsx
- src/shared/components/blocks/dropdown/dropdown.tsx
- src/shared/components/widgets/checkbox/components/checkboxGroup.tsx
- src/shared/components/widgets/forms/components/formField.tsx
- src/shared/constants/const/sideMenu.const.ts
.qa 수행하였습니다.
1.회원가입의 아코디언 컴포넌트 너비 수정
2.회원가입 step3의 폼을 전반적으로 스타일링 수정하였습니다.
3.input의 error 메세지 성공 메세지를 position absoulte로 수정하였습니다.(signup step3와 post register페이지 참조)
mentor-register 페이지(디자이너와 기획자와 이야기 필요,기획과 디자인 불일치)
>이번부터 perfect pixel을 도입하였습니다. figma를 참조하여 비교해 보시기 바랍니다.
> Pulse 379 프론트 qa

- src/app/styles/common/border.css
- src/app/styles/component/form.css
- src/features/auth/signIn/signIn.view.tsx
- src/features/auth/signUp/signUp.view.tsx
- src/features/auth/signUp/steps/signupcertificationstep.tsx
- src/features/auth/signUp/steps/signupformstep.tsx
- src/features/posts/posts.view.tsx
- src/features/register/formsections/stack.ts
- src/features/register/register.controller.tsx
- src/features/register/stepper/schedulecontext/context.tsx
- src/features/register/stepper/threestep.tsx
- src/networks/apis/user.api.ts
- src/networks/client/private.client.ts
- src/shared/components/blocks/datepicker/DatePickerField.tsx
- src/shared/components/widgets/forms/components/formField.tsx
- src/shared/components/widgets/popups/selectedBox.tsx
- src/shared/components/widgets/rePassword/step/naverLogin.tsx
- src/shared/components/widgets/rePassword/step/rePasswordForm.tsx
- src/shared/constants/const/form.const.ts
- src/shared/constants/const/socia.const.ts
- src/shared/modules/text-editor/layers/views/editor.view.tsx
> Pulse 404 qa

- src/app/styles/component/button.css
- src/shared/components/atoms/buttons/baseButton.tsx
> [fix]버튼 컴포넌트

- src/app/styles/common/guide.css
- src/app/styles/common/theme.css
- src/app/styles/component/button.css
- src/features/auth/signUp/signUp.view.tsx
- src/features/auth/signUp/steps/signupconsentstep.tsx
- src/features/auth/signUp/steps/signupformstep.tsx
- src/features/register/formsections/career.tsx
- src/features/register/formsections/certificate.tsx
- src/features/register/formsections/education.tsx
- src/features/register/stepper/onestep.tsx
- src/shared/components/blocks/datepicker/DatePickerField.tsx
- src/shared/components/blocks/dropdown/dropdown.tsx
- src/shared/components/widgets/checkbox/components/checkboxGroup.tsx
- src/shared/modules/modals/shared/contexts/modalContexts.tsx
- src/shared/modules/modals/shared/contexts/modalProvider.tsx
- src/shared/modules/modals/shared/hooks/useModal.ts
- src/shared/modules/select-ui/styles/select.css
> Pulse 390 회원가입 첫 페이지 UI

- src/features/posts/posts.service.tsx
- src/networks/apis/user.api.ts
> fix: 불필요 로그 삭제 (#124)

- src/features/mentor-check/mentor-check.service.tsx
- src/features/posts/posts.service.tsx
- src/networks/apis/user.api.ts
- src/networks/client/private.client.ts
- src/shared/components/widgets/sideMenus/floatingMenu.tsx
- src/shared/constants/const/sideMenu.const.ts
- src/shared/lib/utils/menuActionMap.ts
>멘토정보 클릭시 로그인 유무 확인, 로그인 이후 멘토정보를 클릭하면 멘토등록 여부에 각각 다른 페이지로 이동하는 로직 구현
> Pulse 440 멘토 info exist api 연동

- src/contracts/request/post/post.request.dto.ts
- src/features/chat/view/chatroomdetail/detail.detail.tsx
- src/features/mentee/controller/mentee.controller.tsx
- src/features/posts/posts.service.tsx
- src/features/posts/posts.view.tsx
- src/networks/client/private.client.ts
- src/shared/components/blocks/map/map.tsx
- src/shared/components/blocks/searches/popupSearch.tsx
- src/shared/components/widgets/Mentor/hooks/useMentoringListQuery.ts
- src/shared/components/widgets/Mentor/view/mentorViewMap.tsx
- src/shared/components/widgets/Mentor/view/mentorViewPosts.tsx
- src/shared/components/widgets/popups/local/popup/localPopup.tsx
- src/shared/lib/hooks/useUser.ts
> Pulse 423 posts api 연동확인
